### ISSUE TITLE
Weekly scrum - 03-03-2019

### ISSUE THREAD

**Issue by augusthacks** [Nedla/4806-project#1]
### Alden
- Created the github repo, project with kanban board, Travis CI and Heroku accounts.
- This week I will deploy the initial version of the web-app.

**Comment by CCiaran** [comment]
- Last week I added Maven support to the project, with Spring (web, thymeleaf, JPA), and a simple test framework.
- This week I will create a basic data model and simple user registration and role behaviour.

**Comment by augusthacks** [comment]
Good work.
