### ISSUE TITLE
Weekly Scrum #3

### ISSUE THREAD

**Issue by CCiaran** [Nedla/4806-project#7]

**Comment by augusthacks** [comment]
I added file uploading as an article submitter. Some things still need to be worked on such as file properties, properly listing the files/retrieving/managing them, and storing them as an article object.

This week I will try polishing off the file uploading functionality. I will also try and look into managing users and roles such to limit the actions available to file management. Continuation of issue #5 .

**Comment by CCiaran** [comment]
- Added database initialization.
- Added repo tests.
- Added controller tests. Posted forms are not adequately tested.

This week I will allow editors to assign articles to reviewers. ( #11 )
